name: OreGen
description: A plugin that replaces Cobble Generation with Ore Generation
author: Drekryan
main: com.Drekryan.OreGen.OreGen
version: ${project.version}
commands:
  oregen:
    description: OreGen main command
    usage: /oregen <reload>