package com.Drekryan.OreGen;

import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.Sound;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockFromToEvent;
import org.bukkit.plugin.Plugin;

class BlockListener implements Listener {
    private int DEBUG = 0; //Enable debug messages

    private Plugin plugin;
    private final Material[] oreMaterials = new Material[]{Material.COBBLESTONE, Material.DIAMOND_ORE, Material.EMERALD_ORE, Material.REDSTONE_ORE, Material.LAPIS_ORE, Material.GOLD_ORE, Material.IRON_ORE, Material.COAL_ORE};
    private Location oreLocation;

    BlockListener(Plugin plugin) {
        this.plugin = plugin;
    }

    @EventHandler
    public void onBlockFromTo(BlockFromToEvent event) {
        Block block = event.getBlock();
        Block toBlock  = event.getToBlock();

        if (DEBUG == 1)
            System.out.println("From Block: " + block.getType().toString() + " | " + "To Block: " + toBlock.getType().toString());

        // Check if an ore should be generated by looking for the correct
        // source blocks
        if (shouldGenerate(block.getType(), toBlock)) {
            if (oreLocation != null) {
                event.setCancelled(true);

                if (DEBUG == 1)
                    System.out.println("Ore Location: " + oreLocation.toString());

                //Pick a random ore to spawn
                //TODO: Chance System
                int randomIndex = (int)Math.floor(Math.random() * oreMaterials.length);
                Material ore = oreMaterials[randomIndex];

                //Spawn block and play lava extinguish sound
                if (ore != null) {
                    block.getWorld().getBlockAt(oreLocation).setType(ore);
                    block.getWorld().playSound(block.getLocation(), Sound.BLOCK_LAVA_EXTINGUISH, 1.0f, 1.0f);
                }
            }
        }
    }

    private boolean shouldGenerate(Material blockMaterial, Block toBlock) {
        if (blockMaterial != Material.STATIONARY_LAVA) return false;
        if (toBlock.getType() != Material.AIR) return false;

        BlockFace[] blockFaces = new BlockFace[]{BlockFace.SELF, BlockFace.UP, BlockFace.NORTH, BlockFace.EAST, BlockFace.SOUTH, BlockFace.WEST};
        int length = blockFaces.length;
        int index = 0;

        while (index < length) {
            BlockFace blockFace = blockFaces[index];
            if (DEBUG == 1)
                System.out.println("Found (" + blockFace.toString() + " ): " + toBlock.getRelative(blockFace, 1).getType().toString());

            if (toBlock.getRelative(blockFace, 1).getType() == Material.STATIONARY_WATER) {
                //Set the location of the source block to update
                oreLocation = toBlock.getLocation();
                return true;
            }

            ++index;
        }

        Block belowBlock = toBlock.getRelative(BlockFace.DOWN, 1);
        if (belowBlock.getType() == Material.STATIONARY_WATER) {
            if (DEBUG == 1)
                System.out.println("Found Water -- Creating Stone");
            return false;
        }

        return false;
    }
}
