package com.Drekryan.OreGen;

import com.Drekryan.OreGen.util.ConfigManager;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.Sound;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockFromToEvent;
import org.bukkit.plugin.Plugin;

import java.util.Map;

class BlockListener implements Listener {
    private int DEBUG = 0; //Enable debug messages

    private OreGen plugin;
    private Map<String, Integer> blockValues;
    private Location oreLocation;
    private boolean configInvalid;

    BlockListener(Plugin plugin) {
        this.plugin = (OreGen) plugin;
        plugin.getServer().getPluginManager().registerEvents(this, plugin);

        ConfigManager configManager = this.plugin.getConfigManager();
        blockValues = configManager.getBlockValues();

        int totalPercent = 0;
        for (String blockName : blockValues.keySet()) {
            totalPercent += blockValues.get(blockName);
        }
        if (totalPercent != 100) configInvalid = true;
    }

    @EventHandler
    public void onBlockFromTo(BlockFromToEvent event) {
        Block block = event.getBlock();
        Block toBlock  = event.getToBlock();

        if (DEBUG == 1)
            System.out.println("[OreGen] From Block: " + block.getType().toString() + " | " + "To Block: " + toBlock.getType().toString());

        // Check if an ore should be generated by looking for the correct
        // source blocks
        if (shouldGenerate(block.getType(), toBlock)) {
            if (oreLocation != null) {
                event.setCancelled(true);

                if (DEBUG == 1)
                    System.out.println("[OreGen] Ore Location: " + oreLocation.toString());

                //Pick an ore to spawn
                if (blockValues != null && !configInvalid) {
                    int roll = (int) Math.floor(Math.random() * 100);
                    String spawnBlock = "";

                    if (DEBUG == 1)
                        System.out.println("[OreGen] Picking from " + blockValues.keySet().size() + " values...");

                    for (String blockName : blockValues.keySet()) {
                        int chance = blockValues.get(blockName);

                        if (roll < chance) {
                            spawnBlock = blockName;
                            break;
                        }
                    }

                    //Spawn block and play lava extinguish sound
                    if (spawnBlock.equals("")) spawnBlock = "COBBLESTONE";
                    if (Material.getMaterial(spawnBlock) != null && oreLocation != null) {
                        block.getWorld().getBlockAt(oreLocation).setType(Material.getMaterial(spawnBlock));
                        block.getWorld().playSound(block.getLocation(), Sound.BLOCK_LAVA_EXTINGUISH, 1.0f, 1.0f);
                    }
                } else {
                    plugin.getLogger().warning("Config values did not equal 100%. Skipping..");
                }
            }
        }
    }

    private boolean shouldGenerate(Material blockMaterial, Block toBlock) {
        if (blockMaterial != Material.STATIONARY_LAVA) return false;
        if (toBlock.getType() != Material.AIR) return false;

        BlockFace[] blockFaces = new BlockFace[]{BlockFace.SELF, BlockFace.UP, BlockFace.NORTH, BlockFace.EAST, BlockFace.SOUTH, BlockFace.WEST};
        int length = blockFaces.length;
        int index = 0;

        while (index < length) {
            BlockFace blockFace = blockFaces[index];
            if (DEBUG == 1)
                System.out.println("[OreGen] Found (" + blockFace.toString() + " ): " + toBlock.getRelative(blockFace, 1).getType().toString());

            if (toBlock.getRelative(blockFace, 1).getType() == Material.STATIONARY_WATER) {
                //Set the location of the source block to update
                oreLocation = toBlock.getLocation();
                return true;
            }

            ++index;
        }

        Block belowBlock = toBlock.getRelative(BlockFace.DOWN, 1);
        if (belowBlock.getType() == Material.STATIONARY_WATER) {
            if (DEBUG == 1)
                System.out.println("[OreGen] Found Water -- Creating Stone");
            return false;
        }

        return false;
    }
}
